# Generated by Django 3.0.5 on 2020-07-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physiotherapist', '0001_initial'),
        ('nurse', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPhysio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('problem', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.BookingDate')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('physiotherapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Physiotherapist')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiotherapist.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentNurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('problem', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.BookingDate')),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.Nurse')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.Slot')),
            ],
        ),
    ]
